name: .NET Core

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install tooling
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      env:
        clientId: ${{ secrets.SAFEDEPLOYAPPID }}
        subscriptionId: ${{ secrets.SAFEDEPLOYSUBSCRIPTIONID }}
        clientSecret: ${{ secrets.SAFEDEPLOYSECRET }}
        tenantId: ${{ secrets.SAFEDEPLOYTENANTID }}
      run: >
        dotnet fake build --target appservice
        -e location= "australiaeast"
        -e rgEnvironment = "dev"

