name: .NET Core

on:
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install tooling
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      env:
        SAFEDEPLOYTENANTID: ${{ secrets.SAFEDEPLOYTENANTID }}
      run: echo "$SAFEDEPLOYTENANTID"
    #   dotnet fake build --target appservice
    # -e subscriptionId=<subId>
    # -e clientId=<clientId>
    # -e tenantId=<tenantId>
    # -e environment=<environment> (optional)
    # -e location=<location>       (optional)
    # -e pricingTier=<pricingTier> (optional)
    #- name: Build
    #  run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
